# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AdrLint < Formula
  desc "Automatically validates code changes against Architecture Decision Records using Claude."
  homepage "https://github.com/wbern/adr-lint"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wbern/adr-lint/releases/download/v0.2.0/adr-lint_0.2.0_macos_x86_64.tar.gz"
      sha256 "9f258c496e7648abd9494b01335134cb3c7bbbb385a7c0fb9812e1e9ec5acc8a"

      define_method(:install) do
        bin.install "adr-lint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wbern/adr-lint/releases/download/v0.2.0/adr-lint_0.2.0_macos_arm64.tar.gz"
      sha256 "2e905a7d4a44d1cba1eea173f44eba03088f28f1d6b16b7b1c2237bdc422677b"

      define_method(:install) do
        bin.install "adr-lint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wbern/adr-lint/releases/download/v0.2.0/adr-lint_0.2.0_linux_x86_64.tar.gz"
      sha256 "0bbd58928999b16209936efc2d5d31bbcd566e5825097ed368dd27340b0a73cb"
      define_method(:install) do
        bin.install "adr-lint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wbern/adr-lint/releases/download/v0.2.0/adr-lint_0.2.0_linux_arm64.tar.gz"
      sha256 "1bd93283b60d3b805ee865774724e20a89f28637e2f0d4e5491fd3c660ed7839"
      define_method(:install) do
        bin.install "adr-lint"
      end
    end
  end

  test do
    system "#{bin}/adr-lint", "version"
  end
end
